<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>frames</title>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="fonts/stylesheet.css" type="text/css" rel="stylesheet" />
<!-- jQuery library -->
<script src="js/jquery.min.js"></script>
<link href="css/owl.carousel.css" rel="stylesheet">
<link href="css/owl.theme.css" rel="stylesheet">
<script src="js/jquery-1.9.1.min.js"></script>
<script src="js/owl.carousel.js"></script> 
<!-- Latest compiled JavaScript -->
<script src="js/bootstrap.min.js"></script>
<script>
$(document).ready(function() {
  $("#owl-demo").owlCarousel({
    navigation : true
  });
});

</script>
<link href="css/media.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="main"> 
  
  <!--=========================header==================================-->
  
  <header>
    <div class="top_header">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6 pad_none">
            <p class="call"><a href="callto:">Call us: (800) 269-4149</a></p>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6 pad_none">
            <div class="signin">
              <p><a href="#">Sign in<i class="fa fa-angle-down"></i></a></p>
              <p><span><a href="#">checkout</a></span></p>
            </div>
            <!--sign ends--> 
            
          </div>
        </div>
        <!--row ends--> 
      </div>
    </div>
    <!--top header ends-->
    
    <div class="main_header">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6 pad_none">
            <div class="logo"><a href="index.html"><img src="images/logo.png" alt="logo" title="frames" /></a></div>
            <!--logo ends--> 
          </div>
          <!-- col ends-->
          <div class="col-md-6 col-sm-6 col-xs-6 pad_none">
            <p class="cart"><!--i class="fa fa-shopping-cart"></i--><img class="cart_img" src="images/cart_img.png">my Cart (0)</p>
          </div>
          <!--col ends--> 
        </div>
        <!--row ends-->
        
        <div class="nav_sec">
          <div class="row">
            <div class="col-md-9 col-sm-9 pad_none">
              <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                  </div>
                  <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="#">women</a></li>
                      <li><a href="#">men</a></li>
                      <li><a href="#">Kids</a></li>
                      <li><a href="#">Glasses</a></li>
                      <li><a href="#">Sunglasses</a></li>
                      <li><a href="#">Prescription Sunglasses</a></li>
                      <li><a href="#">Brands</a></li>
                    </ul>
                  </div>
                </div>
              </nav>
            </div>
            <!--col ends-->
            
            <div class="col-md-3 col-sm-3 pad_none">
              <div class="search">
                <form>
                  <input name="" type="text" placeholder="Search brands & trends" />
                </form>
                <div class="serch_icon"><a href="#NULL"></a></div>
              </div>
              <!--search ends--> 
            </div>
            <!--col ends--> 
          </div>
          <!--row ends--> 
        </div>
        <!--nav-sec ends--> 
        
      </div>
    </div>
    <!--main header ends--> 
  </header>
  
  <!--======================banner section======================================-->
  
  <div class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-12 pad_none"> 
       
        	<div id="myCarousel" class="carousel slide" data-ride="carousel">
 
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  
  <div class="carousel-inner" role="listbox">
    
    <div class="item active">
    <div class="slider">
        <div class="col-md-5 slider_txt col-sm-5 col-xs-5">
        	<h2>your endless summer</h2>
            <h3>designer sunglasses</h3>
            <a href="#">shop all sunglasses</a>
        </div><!--ccol ends-->
         <div class="col-md-7 slider_img col-sm-7 col-xs-7"><img src="images/bannimg_01.jpg"  alt="img" /></div><!--col ends-->
        
        </div><!--slider ends-->
 
</div>

    

    <div class="item">
     <div class="slider">
        <div class="col-md-5 slider_txt col-sm-5 col-xs-5">
        	<h2>your endless summer</h2>
            <h3>designer sunglasses</h3>
            <a href="#">shop all sunglasses</a>
        </div><!--ccol ends-->
         <div class="col-md-7 slider_img col-sm-7 col-xs-7"><img src="images/bannimg_02.jpg"  alt="img" /></div><!--col ends-->
        
        </div><!--slider ends-->
 
 </div>
 
<div class="item">
<div class="slider">
        <div class="col-md-5 slider_txt col-sm-5 col-xs-5">
        	<h2>your endless summer</h2>
            <h3>designer sunglasses</h3>
            <a href="#">shop all sunglasses</a>
        </div><!--ccol ends-->
         <div class="col-md-7 slider_img col-sm-7 col-xs-7"><img src="images/bannimg_03.jpg"  alt="img" /></div><!--col ends-->
        
        </div><!--slider ends-->
 
</div> 
<div class="item">
<div class="slider">
        <div class="col-md-5 slider_txt col-sm-5 col-xs-5">
        	<h2>your endless summer</h2>
            <h3>designer sunglasses</h3>
            <a href="#">shop all sunglasses</a>
        </div><!--ccol ends-->
         <div class="col-md-7 slider_img col-sm-7 col-xs-7"><img src="images/bannimg_04.jpg"  alt="img" /></div><!--col ends-->
        
        </div><!--slider ends-->
 
</div>

 
  </div>


  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <i class="fa fa-chevron-left"></i>

  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <i class="fa fa-chevron-right"></i>

  </a>
</div>
        
        
        </div>
        <!--col ends--> 
        
      </div>
      <!--row ends--> 
    </div>
    <!--containor ends--> 
    
  </div>
  <!--banner ends--> 
  
  <!--=======================content===============================================-->
  
  <div class="content">
    <section class="style">
      <div class="container">
        <div class="row">
          <div class="col-md-12 pad_none">
            <div class="outer_h2">
              <h2><img src="images/img_01.png" alt="eye" />Find your style</h2>
            </div>
            <!--outer_h2 ends--> 
          </div>
          <!--col ends--> 
        </div>
        <!--row ends-->
        
        <div class="select">
          <div class="row">
            <div class="col-md-12 pad_none">
              <form>
                <samp>
                <label>Price </label>
                <select>
                  <option>ALL</option>
                </select>
                </samp> <samp>
                <label>Brand</label>
                <select>
                  <option>ALL</option>
                </select>
                </samp> <samp>
                <label>Color</label>
                <select id="all_select">
                  <option>ALL</option>
                </select>
                </samp> <samp>
                <label>Frame Type</label>
                <select>
                  <option>ALL</option>
                </select>
                </samp> <samp>
                <label>Gender</label>
                <select>
                  <option>ALL</option>
                </select>
                </samp> <samp>
                <label>Rim Type</label>
                <select id="all_select">
                  <option>ALL</option>
                </select>
                </samp> <samp>
                <label>Frame Shape</label>
                <select id="all_select">
                  <option>ALL</option>
                </select>
                </samp> <samp class="submit">
                <input name="" type="submit" value="find" />
                </samp>
              </form>
            </div>
            <!--col ends--> 
          </div>
          <!--row ends--> 
        </div>
        <!--select ends--> 
        
      </div>
      <!--containor ends--> 
    </section>
    <section class="featured_prod">
      <div class="container">
        <div class="row">
          <div class="col-md-12 pad_none">
            <div class="outer_h2">
              <h2>Featured Products</h2>
            </div>
            <!--outer_h2 ends--> 
          </div>
          <!--col ends--> 
        </div>
        <!--row ends-->
        
        <div class="products">
          <div class="row">
            <div class="col-md-12 pad_none">
              <div class="panel-group">
                <div class="panel panel-default" id="product_1_5_9">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default" id="product_4_8_12">
                	<div class="new_img_otr"><img src="images/new_img.png"  alt="" /></div>
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default" id="product_1_5_9">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
                <div class="panel panel-default" id="product_4_8_12">
                  <div class="panel-body">
                    <div class="panel_img"><span><a href="#"><img src="images/img_04.jpg"  alt="glasses" /></a></span></div>
                    <!--panel img ends-->
                    <div class="panel_txt">
                      <h3>Carrera 7594 Glasses</h3>
                      <span>$128.00</span> <a href="#">View Details</a> </div>
                    <!--panel txt ends--> 
                  </div>
                </div>
              </div>
            </div>
            <!--col ends--> 
          </div>
          <!--row ends--> 
          
        </div>
        <!--products ends--> 
        
      </div>
      <!--containor ends--> 
      
    </section>
    <section class="pick">
      <div class="container">
        <div class="row">
          <div class="col-md-12 pad_none">
          	<div class="col-sm-6 col-md-6 col-xs-12 pad_none" id="cont_two_imgs">
            	<div class="col-sm-6 col-md-6 col-xs-6 pad_none" id="cont_one_imgs">
                    <h2>Sales</h2>
                    <a href="#">Click H<strong></strong>ere</a>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-6 pad_none" id="cont_sec_imgs">
                    <h2>Summer</h2>
                    <h2 id="fav">Favorites</h2>
                    <a href="#">Click Here</a>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-xs-12 pad_none" id="cont_single_imgs">
                <h2>Editors Pick's</h2>
                <a href="#">Click Here</a>
            </div>
          </div>
          <!--col ends--> 
          
        </div>
        <!--row ends--> 
        
      </div>
      <!--containor ends--> 
      
    </section>
    <section class="client_logo">
      <div class="container">
        <div class="row">
          <div class="col-md-11 col-sm-11 col-xs-12 pad_none">
            <ul>
              <li><span><img src="images/clientlogo_01.jpg" alt="clientlogo" /></span></li>
              <li><span><img src="images/clientlogo_02.jpg" alt="clientlogo" /></span></li>
              <li><span><img src="images/clientlogo_03.jpg" alt="clientlogo" /></span></li>
              <li><span><img src="images/clientlogo_04.jpg" alt="clientlogo" /></span></li>
              <li><span><img src="images/clientlogo_05.jpg" alt="clientlogo" /></span></li>
            </ul>
          </div>
          <!--col ends-->
          <div class="col-md-1 col-sm-1 col-xs-12 pad_none"><a href="#">view all</a></div>
          <!--col ends--> 
        </div>
        <!--row ends--> 
        
      </div>
      <!--containoe ends--> 
    </section>
  </div>
  <!--content ends--> 
  
  <!--===========================footer=========================================-->
  
  <footer>
    <div class="footer_nav">
      <div class="container">
        <div class="row">
          <div class="col-md-12 pad_none">
            <ul>
              <li><a href="index.html">Home</a></li>
              <li><a href="index.html">Sitemap</a></li>
              <li><a href="index.html">Advanced Search</a></li>
              <li><a href="index.html">About Us</a></li>
              <li><a href="index.html">Contact Us</a></li>
              <li><a href="index.html">Privacy Policy</a></li>
              <li><a href="index.html">Orders & Returns</a></li>
              <li><a href="index.html">FAQs</a></li>
            </ul>
          </div>
          <!--col ends--> 
        </div>
        <!--row ends--> 
      </div>
    </div>
    <!--footer nav ends-->
    <div class="footer_main_sec">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4 col-xs-12 para_one">
            <h3>10% OFF For New Members</h3>
            <p>Because Loyalty Knows No Bounds. Sign 
              up now and receive 10% OFF your next 
              purchase. </p>
            <a href="#">Register Account</a> </div>
          <!--col ends-->
          <div class="col-md-5 col-sm-5 col-xs-12 para_second">
            <h3>Free Shipping & Free Returns</h3>
            <p>No Hassle Shipping & Returns. 
              Orders Ship Free & Return Free. We 
              know finding the right pair of frames 
              isn't easy. Come experience what 
              eCommerce should be like. </p>
          </div>
          <!--col ends-->
          <div class="col-md-3 col-sm-3 col-xs-12 para_third">
            <h3>stay up to date</h3>
            <p>Enter your email address for our daily 
              updates, new arrival, new products and 
              more...</p>
            <div class="mail">
              <form>
                <samp>
                <input name="" type="text" value="Your email." />
                <input name="" type="submit" value=""  />
                </samp>
              </form>
            </div>
            <!--mail ends--> 
          </div>
          <!--col ends--> 
          
        </div>
      </div>
    </div>
    <!--footer main ends-->
    <div class="footer_bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12 pad_none">
            <p>Copyright © 2015 | Frames21.Com | All Rights Reserved.</p>
          </div>
          <!--col ends-->
          <div class="col-md-6 col-sm-6 col-xs-12 pad_none">
            <div class="sc_icons">
              <p>cONNECT WITH US</p>
              <ul>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              </ul>
            </div>
            <!--sc_icons ends--> 
          </div>
          <!--col ends--> 
          
        </div>
      </div>
    </div>
    <!--footer bottom ends--> 
  </footer>
</div>
<!--main ends-->
</body>
</html>
